service: whistle-backend-api

provider:
  name: aws
  runtime: java8
  stage: dev
  region: us-west-2
  memorySize: 512

package:
  artifact: build/libs/whistle-dev-all.jar

functions:
  greet:
    handler: com.smackwerks.whistle.api.Schedule::greet
    events:
      - http:
          path: schedule/greet
          method: get
  hello:
    handler: com.serverless.Handler

