service: whistle-backend-api

provider:
  name: aws
  runtime: java8
  stage: dev
  region: us-east-1

package:
  artifact: build/libs/whistle-dev-all.jar

functions:
  hello:
    handler: com.smackwerks.whistle.api.Schedule
    events:
      - http:
          path: schedule
          method: get

plugins:
  - serverless-offline
